title: Temple News Agency
title_stub: Specialty Coffee and Ice Cream in LaPorte, IN 46350
name: J.D. Flynn
email: jflynn8@gmail.com
description: "LaPorte, Indiana's favorite spot for the best coffee and ice cream in town.  Located at 816 Jefferson Ave in LaPorte, Temple News Agency proudly serves specialty coffee drinks, hand dipped ice cream, pastries, and lunch and breakfast specials."
homepage_text: "<p class='header col s12 light'>LaPorte, Indiana's favorite spot for the best coffee and ice cream in town.</p><p class='header col s12 light'>Located at 816 Jefferson Ave in LaPorte, Temple News Agency proudly serves specialty coffee drinks with Intelligentsia Coffee, hand dipped ice cream from Sherman's Ice Cream, pastries, and lunch and breakfast specials.</p>"
baseurl: ""
url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

logo: assets/images/transparent-logo.png
logo_description: 'Temple News Agency logo'

parallax_image_one: assets/images/Temple4.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/Temple13.jpg

project_one: "100 Years of Temple"
project_one_description: Thanks a latte for all your support!
project_one_image: assets/images/Temple15.jpg


project_two: Proudly serving Intelligentsia Coffee
project_two_description: We serve freshly roasted El Diablo Dark Roast and Black Cat Espresso
project_two_image: assets/images/Temple12.jpg


project_three: It's not just a clever name
project_three_description: Temple takes its name from the Masonic Temple, built in 1913, where it has been since 1918
project_three_image: assets/images/Temple8.jpg


project_four: A gathering place
project_four_description: Temple has a collection of local yearbooks from the 1920s through today to browse through.
project_four_image: assets/images/Temple13.jpg

portfolio_heading: Featured Items
portfolio_type: carousel

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

icon_size: 50 # font-size of icons in px
logo_size: 200
colored: colored # Leave blank for black and white icons

project_button: Github

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: "" #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: UA-126824911-1

#cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: false # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-compress-images

compress_images:
  images_path: "assets/images/**/*.{gif,png,jpg,jpeg,svg}"

logos:
  - name: Intelligentsia
    uri: assets/images/Intelligentsia_logo.png
  - name: Coffee Masters
    uri: assets/images/CM-Logo-New.png
  - name: Sherman's Ice Cream
    uri: assets/images/shermans-ice-cream-logo-200.png
  - name: Dagger Mountain
    uri: assets/images/dagger-mountain.jpg

exclude: [_compress_images_cache.yml]